//! AST-based Validation
//!
//! traverse the syntax tree to find errors and semantic issues.

use super::languages::SupportedLanguage;
use tree_sitter::{Tree, TreeCursor};

#[derive(Debug, Clone, PartialEq)]
pub enum ValidationErrorType {
    SyntaxError,   // Parser found explicit error (red node)
    MissingToken,  // Parser expected a token but didn't find it
    SemanticError, // Code is syntactically valid but semantically wrong (e.g. self outside class)
}

#[derive(Debug, Clone)]
pub struct ValidationError {
    pub error_type: ValidationErrorType,
    pub message: String,
    pub line: usize,  // 1-based line number
    #[allow(dead_code)]
    pub column: usize,
}

pub struct AstValidator;

impl AstValidator {
    /// Prawdziwa walidacja świadoma AST (Comparative Analysis)
    pub fn validate_structure_integrity(original: &str, patched: &str) -> bool {
        use crate::apply_system::analysis::AnalysisEngine;

        // Ponieważ nie mamy tutaj jawnej ścieżki do pliku, a AnalysisEngine::parse 
        // potrzebuje jej do wykrycia języka, musimy wdrożyć uniwersalne sprawdzenie.
        // Zakładamy na razie heurystykę: próbujemy sparsować jako Python, a jak nie, to jako Rust/JS.
        let lang_hint = if original.contains("def ") || original.contains("class ") {
            "dummy.py"
        } else if original.contains("fn ") || original.contains("impl ") {
            "dummy.rs"
        } else {
            "dummy.ts"
        };

        // 1. Parsowanie oryginału
        let original_errors = match AnalysisEngine::parse(original, lang_hint) {
            Ok(tree) => Self::count_ast_errors(&tree),
            Err(_) => return true, // Język nieobsługiwany, przepuszczamy
        };

        // 2. Parsowanie zmodyfikowanego kodu
        let patched_errors = match AnalysisEngine::parse(patched, lang_hint) {
            Ok(tree) => Self::count_ast_errors(&tree),
            Err(_) => return true,
        };

        // Jeśli zmodyfikowany kod ma więcej błędów kompilacji (AST ERRORs) 
        // niż oryginał, to znaczy że patch zniszczył strukturę.
        if patched_errors > original_errors {
            crate::gluon_warn!("AstValidator", "Wykryto zniszczenie struktury AST! Błędy: {} -> {}", original_errors, patched_errors);
            return false;
        }

        true
    }

    /// Zlicza węzły ERROR oraz MISSING w drzewie AST.
    fn count_ast_errors(tree: &tree_sitter::Tree) -> usize {
        let mut count = 0;
        let mut cursor = tree.root_node().walk();

        let mut stack = vec![tree.root_node()];
        while let Some(node) = stack.pop() {
            if node.is_error() || node.is_missing() {
                count += 1;
            }

            for child in node.children(&mut cursor) {
                stack.push(child);
            }
        }
        count
    }
}

impl AstValidator {
    /// Validates the syntax tree for errors and language-specific semantic rules.
    pub fn validate(code: &str, tree: &Tree, language: SupportedLanguage) -> Vec<ValidationError> {
        let mut errors = Vec::new();

        // 1. Generic Syntax Validation (ERROR / MISSING nodes)
        Self::collect_syntax_errors(tree, &mut errors);

        // 2. Language-Specific Semantic Validation
        match language {
            SupportedLanguage::Python => {
                Self::validate_python_semantics(code, tree, &mut errors);
            }
            _ => {} // Other languages can be added here
        }

        errors
    }

    /// Walks the tree to find generic syntax errors generated by Tree-sitter.
    fn collect_syntax_errors(tree: &Tree, errors: &mut Vec<ValidationError>) {
        let root = tree.root_node();
        let mut cursor = root.walk();

        // Standard recursive walk is sufficient for error finding
        Self::walk_for_errors(&mut cursor, errors);
    }

    fn walk_for_errors(cursor: &mut TreeCursor, errors: &mut Vec<ValidationError>) {
        let node = cursor.node();

        // Check current node
        if node.is_error() {
            // Tree-sitter ERROR node
            let start = node.start_position();
            // Try to extract content if possible, or just generic message
            errors.push(ValidationError {
                error_type: ValidationErrorType::SyntaxError,
                message: format!("Syntax error (unexpected token type: {})", node.kind()),
                line: start.row + 1,
                column: start.column,
            });
            // We usually don't need to descend into an ERROR node, but sometimes it helps
        } else if node.is_missing() {
            let start = node.start_position();
            errors.push(ValidationError {
                error_type: ValidationErrorType::MissingToken,
                message: format!("Missing expected token: {}", node.kind()),
                line: start.row + 1,
                column: start.column,
            });
        }

        // Recurse children
        if cursor.goto_first_child() {
            loop {
                Self::walk_for_errors(cursor, errors);
                if !cursor.goto_next_sibling() {
                    break;
                }
            }
            cursor.goto_parent();
        }
    }

    /// Python-specific checks (e.g., ensuring `self` is used inside classes).
    fn validate_python_semantics(code: &str, tree: &Tree, errors: &mut Vec<ValidationError>) {
        let root = tree.root_node();
        let mut cursor = root.walk();
 
        // Traverse specifically looking for function definitions
        Self::walk_python_functions(code, &mut cursor, errors);
        
        // [GLUON HARDENING] Structural Integrity Check
        Self::validate_python_structure(code, tree, errors);
    }
 
    fn is_inside_function(mut node: tree_sitter::Node) -> bool {
        while let Some(parent) = node.parent() {
            if parent.kind() == "function_definition" {
                return true;
            }
            node = parent;
        }
        false
    }
 
    /// Validates proper placement of control flow statements and return/yield
    fn validate_python_structure(code: &str, tree: &Tree, errors: &mut Vec<ValidationError>) {
        let root = tree.root_node();
        let mut cursor = root.walk();
        
        // Recursive traversal to check node placement
        // We avoid recursion for performance, using a stack instead
        let mut stack = vec![root];
        
        while let Some(node) = stack.pop() {
            let kind = node.kind();
            
            // Check 1: Return/Yield outside function
            if kind == "return_statement" || kind == "yield_statement" {
                if !Self::is_inside_function(node) {
                     errors.push(ValidationError {
                        error_type: ValidationErrorType::SemanticError, // Using SemanticError for flow violations
                        message: format!("Control flow statement '{}' found outside of function definition.", kind),
                        line: node.start_position().row + 1,
                        column: node.start_position().column,
                    });
                }
            }
            
            // Check 2: Logic flow directly in Class Body
            // e.g. "if data.get(...)" directly inside class, orphaned from method
            if kind == "if_statement" || kind == "for_statement" || kind == "while_statement" || kind == "try_statement" {
                if let Some(parent) = node.parent() {
                    if parent.kind() == "class_definition" {
                        // Exception: "if TYPE_CHECKING:" is valid type hint pattern
                        let is_safe = if kind == "if_statement" {
                            if let Ok(text) = node.utf8_text(code.as_bytes()) {
                                text.contains("TYPE_CHECKING")
                            } else { false }
                        } else { false };
 
                        if !is_safe {
                             errors.push(ValidationError {
                                error_type: ValidationErrorType::SemanticError,
                                message: format!("Statement '{}' found directly in class body. This usually indicates broken indentation (orphaned code).", kind),
                                line: node.start_position().row + 1,
                                column: node.start_position().column,
                            });
                        }
                    }
                }
            }
 
            // Push children
            for child in node.children(&mut cursor) {
                stack.push(child);
            }
        }
    }

    /// [GLUON PYTHON INDENT GUARD] Validates that a Python replace_code block has valid
    /// relative indentation — detects impossible nesting of statements inside non-structural lines.
    ///
    /// Problem this catches (BUG 2 from analysis):
    ///   `cd, created = something()`   # 8 spaces — assignment, creates NO block
    ///       `if created:`              # 12 spaces — nested, IMPOSSIBLE in Python
    ///
    /// In Python only lines ending with `:`, `(`, `[`, `{`, `\` can have nested code.
    /// Returns Err with a detailed message if impossible nesting is detected.
    pub fn validate_python_impossible_nesting(code: &str) -> Result<(), String> {
        let get_indent = |line: &str| -> usize {
            let mut indent = 0usize;
            for c in line.chars() {
                match c {
                    ' ' => indent += 1,
                    '\t' => indent += 4,
                    _ => break,
                }
            }
            indent
        };

        let opens_block = |line: &str| -> bool {
            let trimmed = line.trim_end();
            // Lines that legally allow deeper-indented next line in Python
            trimmed.ends_with(':')
                || trimmed.ends_with('(')
                || trimmed.ends_with('[')
                || trimmed.ends_with('{')
                || trimmed.ends_with('\\')
                || trimmed.ends_with("->") // Rust/type hint arrow (rare in search_code context)
                || trimmed.ends_with(',')  // Multi-line argument list
                || trimmed.ends_with('=')  // Multi-line assignment continuation
                || trimmed.ends_with("and")
                || trimmed.ends_with("or")
                || trimmed.ends_with("not")
                || trimmed.ends_with("in")
                || trimmed.ends_with("is")
        };

        // Collect non-empty, non-comment code lines with their indentation
        let meaningful_lines: Vec<(&str, usize)> = code
            .lines()
            .filter(|l| {
                let t = l.trim();
                !t.is_empty() && !t.starts_with('#') && !t.starts_with("//")
            })
            .map(|l| (l, get_indent(l)))
            .collect();

        for window in meaningful_lines.windows(2) {
            let (curr_line, curr_indent) = window[0];
            let (next_line, next_indent) = window[1];

            // If next line is MORE indented than current, current must open a block
            if next_indent > curr_indent && !opens_block(curr_line) {
                return Err(format!(
                    "Invalid Python indentation in replace_code: \
                    '{}' (indent={}) is followed by '{}' (indent={}) without a block opener (':' etc.). \
                    An assignment or expression cannot have nested code. \
                    Both statements should likely be at the same indentation level.",
                    curr_line.trim(),
                    curr_indent,
                    next_line.trim(),
                    next_indent
                ));
            }
        }

        Ok(())
    }

    /// [GLUON JSX BRACKET GUARD] Validates that replace_code for JSX/JS/TS files has balanced
    /// brackets. An unbalanced replacement indicates a partial/incomplete model output that
    /// would corrupt the JSX structure.
    ///
    /// Catches BUG 3: model changed `.map(c => {` to `.reduce((acc, c, idx) => {` but
    /// the replace_code ended mid-element without closing the JSX tag or the callback.
    ///
    /// Returns Err if brackets are unbalanced, Ok otherwise.
    pub fn validate_jsx_bracket_balance(code: &str) -> Result<(), String> {
        use crate::apply_system::matchers::utils::StructuralState;

        let mut state = StructuralState::default();
        for line in code.lines() {
            state.update(line);
        }

        if state.balance != 0 {
            let direction = if state.balance > 0 { "more opens than closes" } else { "more closes than opens" };
            return Err(format!(
                "replace_code has unbalanced brackets (net balance={}; {}). \
                The replacement is likely incomplete — a JSX element or callback was opened but not closed. \
                Ensure the full structural unit (JSX tag, function body, array) is included in replace_code.",
                state.balance,
                direction
            ));
        }

        Ok(())
    }

    /// Collects AST error lines from a tree for comparison (Fix 5: line-based leniency).
    /// Returns a set of (line, column) for each ERROR or MISSING node.
    pub fn collect_ast_error_positions(tree: &tree_sitter::Tree) -> Vec<(usize, usize)> {
        let mut positions = Vec::new();
        let mut stack = vec![tree.root_node()];
        let mut cursor = tree.root_node().walk();

        while let Some(node) = stack.pop() {
            if node.is_error() || node.is_missing() {
                let pos = node.start_position();
                positions.push((pos.row + 1, pos.column)); // 1-based line
            }
            for child in node.children(&mut cursor) {
                stack.push(child);
            }
        }
        positions
    }

    fn walk_python_functions(code: &str, cursor: &mut TreeCursor, errors: &mut Vec<ValidationError>) {
        let node = cursor.node();

        if node.kind() == "function_definition" {
            // Check 1: Function must have a body (not just a pass or empty)
            if let Some(body) = node.child_by_field_name("body") {
                // Body exists, check if it's truly empty (no statements)
                let mut body_cursor = body.walk();
                let has_statements = body.children(&mut body_cursor)
                    .any(|child| {
                        // Check if there's any real statement (not just comments)
                        let kind = child.kind();
                        kind != "comment" && !kind.is_empty()
                    });

                if !has_statements {
                    let start = node.start_position();
                    errors.push(ValidationError {
                        error_type: ValidationErrorType::SyntaxError,
                        message: "Function definition must have a body (add 'pass' if empty)".to_string(),
                        line: start.row + 1,
                        column: start.column,
                    });
                }
            } else {
                // No body field found at all - syntax error
                let start = node.start_position();
                errors.push(ValidationError {
                    error_type: ValidationErrorType::SyntaxError,
                    message: "Function definition missing body".to_string(),
                    line: start.row + 1,
                    column: start.column,
                });
            }

            // Check 2: Arguments for 'self' parameter
            if let Some(params) = node.child_by_field_name("parameters") {
                let mut param_cursor = params.walk();
                for child in params.children(&mut param_cursor) {
                    // Simple check: if first param text is "self"
                    if let Ok(text) = child.utf8_text(code.as_bytes()) {
                        if text == "self" {
                            // Found 'self'. Check ancestors for 'class_definition'.
                            let mut parent = node.parent();
                            let mut inside_class = false;

                            while let Some(p) = parent {
                                if p.kind() == "class_definition" {
                                    inside_class = true;
                                    break;
                                }
                                parent = p.parent();
                            }

                            if !inside_class {
                                let start = child.start_position();
                                errors.push(ValidationError {
                                    error_type: ValidationErrorType::SemanticError,
                                    message: "Method defined with 'self' outside of a class context.".to_string(),
                                    line: start.row + 1,
                                    column: start.column,
                                });
                            }
                            // Only check the first 'self', usually sufficient
                            break; 
                        }
                    }
                }
            }
        }

        // Recurse
        if cursor.goto_first_child() {
            loop {
                Self::walk_python_functions(code, cursor, errors);
                if !cursor.goto_next_sibling() {
                    break;
                }
            }
            cursor.goto_parent();
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::apply_system::analysis::AnalysisEngine;

    #[test]
    fn test_syntax_error_detection() {
        let code = "def foo()  pass"; // Missing colon
        let tree = AnalysisEngine::parse(code, "test.py").unwrap();
        let errors = AstValidator::validate(code, &tree, SupportedLanguage::Python);

        assert!(!errors.is_empty());
        assert!(errors.iter().any(|e| e.error_type == ValidationErrorType::MissingToken || e.error_type == ValidationErrorType::SyntaxError));
    }

    #[test]
    fn test_python_semantic_self_check() {
        let code = "def my_func(self): pass"; // 'self' outside class
        let tree = AnalysisEngine::parse(code, "test.py").unwrap();
        let errors = AstValidator::validate(code, &tree, SupportedLanguage::Python);

        assert!(!errors.is_empty());
        let err = &errors[0];
        assert_eq!(err.error_type, ValidationErrorType::SemanticError);
        assert!(err.message.contains("outside of a class"));
    }

    #[test]
    fn test_python_valid_class_method() {
        let code = "class A:\n    def my_func(self): pass";
        let tree = AnalysisEngine::parse(code, "test.py").unwrap();
        let errors = AstValidator::validate(code, &tree, SupportedLanguage::Python);

        assert!(errors.is_empty());
    }

    #[test]
    fn test_python_impossible_nesting_assignment_then_if() {
        // BUG 2 pattern: `cd, created = ...` followed by `    if created:` (nested inside assignment)
        let code = "        cd, created = Something.objects.update_or_create()\n            if created:\n                cd.save()";
        let result = AstValidator::validate_python_impossible_nesting(code);
        assert!(result.is_err(), "Should detect impossible nesting");
        let msg = result.unwrap_err();
        assert!(msg.contains("block opener"), "Error should mention block opener: {}", msg);
    }

    #[test]
    fn test_python_valid_nesting_after_colon() {
        // Valid: for loop with body
        let code = "        for item in items:\n            process(item)\n            save(item)";
        let result = AstValidator::validate_python_impossible_nesting(code);
        assert!(result.is_ok(), "For loop body should be valid: {:?}", result);
    }

    #[test]
    fn test_python_valid_nesting_after_if() {
        // Valid: if with body at same level as surrounding code
        let code = "        cd, created = x()\n        if created:\n            cd.save()";
        let result = AstValidator::validate_python_impossible_nesting(code);
        assert!(result.is_ok(), "If body at correct level should be valid: {:?}", result);
    }

    #[test]
    fn test_python_impossible_nesting_function_call_then_code() {
        // BUG pattern: expression followed by deeper-indented statement
        let code = "    result = compute()\n        process(result)";
        let result = AstValidator::validate_python_impossible_nesting(code);
        assert!(result.is_err(), "Should detect orphaned nested code after expression");
    }
}